# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Europe/Minsk&useSSL=false
    username: root
    password: qwerty12
    driverClassName: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 128KB
#      max-request-size: 128KB

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO